### Create

In [2]:
import numpy as np

In [3]:
data= np.random.rand(2,3,4)
print(data)

array([[[0.20890796, 0.3252132 , 0.08461507, 0.00393821],
        [0.04557201, 0.28734986, 0.21669746, 0.87997069],
        [0.75704148, 0.59679989, 0.58898195, 0.45408389]],

       [[0.66156625, 0.56582843, 0.80550399, 0.627764  ],
        [0.82499385, 0.76719222, 0.32453754, 0.24028649],
        [0.15328693, 0.00355823, 0.22834881, 0.67083837]]])

In [5]:
zeros= np.zeros((2,2,2))
print(zeros)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [7]:
full= np.full((2,2,2),7)
print(full)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [9]:
ones= np.ones((2,2,2))
print(ones)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [14]:
arr= np.array([3,2,6,87,90])
print(arr)
type(arr)

[ 3  2  6 87 90]


numpy.ndarray

### Read


In [16]:
shape= data.shape
size= data.size
types= data.dtype

In [17]:
types

dtype('float64')

In [31]:
arr= data[0]
# slicer --> gives element from 0-2 excluding 2th index element
slicer= data[0][0:2]
# grabing the last element
reverse= data[-1]
# grabing the single leval element
singleLevel= data[0][0][0] 


In [27]:
slicer

array([[0.20890796, 0.3252132 , 0.08461507, 0.00393821],
       [0.04557201, 0.28734986, 0.21669746, 0.87997069]])

In [29]:
reverse

array([[0.66156625, 0.56582843, 0.80550399, 0.627764  ],
       [0.82499385, 0.76719222, 0.32453754, 0.24028649],
       [0.15328693, 0.00355823, 0.22834881, 0.67083837]])

In [33]:
singleLevel

0.208907964292822

### Update

In [40]:
list1= np.random.rand(10)
list2= np.random.rand(10)

In [45]:
# Basic Maths
add= np.add(list1,list2)
subtract= np.subtract(list1,list2)
mul= np.multiply(list1,list2)
divide= np.divide(list1,list2)
# dot-->gives the dot product

dot = np.dot(list1,list2)


In [46]:
add

array([0.63148552, 0.49190658, 1.53090969, 0.72275239, 0.99357736,
       0.3330011 , 1.01456348, 1.09567981, 1.09514241, 1.16495472])

In [47]:
dot

1.820098233341056

In [53]:
# statistical functions
# S-A-P-L-E-M-M
srt= np.sqrt(25)  
absolute= np.abs([-12,-123])
power= np.power(2,5)
log= np.log(25)
exp= np.exp([2,4])
maxs= np.max(list1)
mins= np.min(list1)


In [56]:
mins

0.003989391134087472

In [57]:
data[0][0][0]= 700
data

array([[[7.00000000e+02, 3.25213200e-01, 8.46150664e-02, 3.93821029e-03],
        [4.55720083e-02, 2.87349860e-01, 2.16697463e-01, 8.79970692e-01],
        [7.57041477e-01, 5.96799888e-01, 5.88981949e-01, 4.54083887e-01]],

       [[6.61566247e-01, 5.65828434e-01, 8.05503994e-01, 6.27763998e-01],
        [8.24993849e-01, 7.67192218e-01, 3.24537535e-01, 2.40286494e-01],
        [1.53286935e-01, 3.55823274e-03, 2.28348809e-01, 6.70838369e-01]]])

In [58]:
data.sort()
data

array([[[3.93821029e-03, 8.46150664e-02, 3.25213200e-01, 7.00000000e+02],
        [4.55720083e-02, 2.16697463e-01, 2.87349860e-01, 8.79970692e-01],
        [4.54083887e-01, 5.88981949e-01, 5.96799888e-01, 7.57041477e-01]],

       [[5.65828434e-01, 6.27763998e-01, 6.61566247e-01, 8.05503994e-01],
        [2.40286494e-01, 3.24537535e-01, 7.67192218e-01, 8.24993849e-01],
        [3.55823274e-03, 1.53286935e-01, 2.28348809e-01, 6.70838369e-01]]])

In [59]:
# reshaping the data
print(data.shape)

(2, 3, 4)


In [64]:
data= data.reshape((2,2,-1))
print(data.shape)
print(data)

(2, 2, 6)
[[[3.93821029e-03 8.46150664e-02 3.25213200e-01 7.00000000e+02
   4.55720083e-02 2.16697463e-01]
  [2.87349860e-01 8.79970692e-01 4.54083887e-01 5.88981949e-01
   5.96799888e-01 7.57041477e-01]]

 [[5.65828434e-01 6.27763998e-01 6.61566247e-01 8.05503994e-01
   2.40286494e-01 3.24537535e-01]
  [7.67192218e-01 8.24993849e-01 3.55823274e-03 1.53286935e-01
   2.28348809e-01 6.70838369e-01]]]


In [67]:
# appending the array
zeroes= np.zeros((8))
print(zeroes)
zeroes= np.append(zeroes,[3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [71]:
# inserting at specific location
zeroes= np.insert(zeroes,2,5)
print(zeroes)

[0. 0. 5. 5. 5. 5. 0. 0. 0. 0. 0. 0. 3. 4.]


### Delete

In [72]:
data

array([[[3.93821029e-03, 8.46150664e-02, 3.25213200e-01, 7.00000000e+02,
         4.55720083e-02, 2.16697463e-01],
        [2.87349860e-01, 8.79970692e-01, 4.54083887e-01, 5.88981949e-01,
         5.96799888e-01, 7.57041477e-01]],

       [[5.65828434e-01, 6.27763998e-01, 6.61566247e-01, 8.05503994e-01,
         2.40286494e-01, 3.24537535e-01],
        [7.67192218e-01, 8.24993849e-01, 3.55823274e-03, 1.53286935e-01,
         2.28348809e-01, 6.70838369e-01]]])

In [76]:
# deleting the row
data=np.delete(data,0,axis=1)

In [77]:
# saving the array 
np.save("new_array",data)

In [78]:
# loading the saved array'
test= np.load("new_array.npy")
test

array([[[0.28734986, 0.87997069, 0.45408389, 0.58898195, 0.59679989,
         0.75704148]],

       [[0.76719222, 0.82499385, 0.00355823, 0.15328693, 0.22834881,
         0.67083837]]])